default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: mysql
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
